name: Windows CI

concurrency:
  # for PR's cancel the running task, if another commit is pushed
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  workflow_dispatch:

  pull_request:
    types: [opened, reopened, edited]
    branches:
      - 'main'    

jobs:
  Windows-build:
    name: Build on Windows 2019
    runs-on: windows-2019

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        submodules: 'recursive'

    - uses: msys2/setup-msys2@v2
      with:
        release: true
        msystem: UCRT64
        update: true
        install: make mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-ninja mingw-w64-ucrt-x86_64-openssl mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-boost

    - name: Cmake configure and build
      run: |
        echo "/ucrt64/bin" >> $GITHUB_PATH
        echo "/usr/bin" >> $GITHUB_PATH
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
        cmake --build build
  
